apiVersion: nais.io/v1alpha1
kind: Application
metadata:
  name: dp-vedtak-iverksett
  namespace: teamdagpenger
  labels:
    team: teamdagpenger
spec:
  image: {{ image }}
  port: 8080
  prometheus:
    enabled: true
    path: /metrics
  replicas:
    min: 1
    max: 1
  resources:
    limits:
      memory: 512Mi
    requests:
      memory: 256Mi
  secureLogs:
    enabled: true
  azure:
    application:
      enabled: true
  gcp:
    sqlInstances:
      - type: POSTGRES_15
        highAvailability: true
        diskAutoresize: true
        pointInTimeRecovery: true
        tier: {{gcp.sql.tier}}
        databases:
          - name: vedtak-iverksett
            envVarPrefix: DB
  accessPolicy:
    outbound:
      rules:
        - application: dp-iverksett
  env:
    - name: DP_IVERKSETT_URL
      value: {{dp-iverksett.url}}
    - name: DP_IVERKSETT_SCOPE
      value: {{dp-iverksett.scope}}

  kafka:
    pool: {{ kafka_pool }}
